/** 100 commonly taught English irregular verbs. Forms separated by / are accepted alternatives. */
export const VERBS = [
['arise','arose','arisen','surgir'],
['awake','awoke','awoken','despertar'],
['be','was / were','been','ser / estar'],
['bear','bore','borne','soportar / llevar'],
['beat','beat','beaten','golpear / vencer'],
['become','became','become','convertirse en'],
['begin','began','begun','comenzar'],
['bend','bent','bent','doblar'],
['bet','bet','bet','apostar'],
['bite','bit','bitten','morder'],
['bleed','bled','bled','sangrar'],
['blow','blew','blown','soplar'],
['break','broke','broken','romper'],
['bring','brought','brought','traer'],
['build','built','built','construir'],
['burn','burnt / burned','burnt / burned','quemar'],
['buy','bought','bought','comprar'],
['catch','caught','caught','atrapar'],
['choose','chose','chosen','elegir'],
['come','came','come','venir'],
['cost','cost','cost','costar'],
['cut','cut','cut','cortar'],
['deal','dealt','dealt','tratar / repartir'],
['dig','dug','dug','cavar'],
['do','did','done','hacer'],
['draw','drew','drawn','dibujar'],
['dream','dreamt / dreamed','dreamt / dreamed','soñar'],
['drink','drank','drunk','beber'],
['drive','drove','driven','conducir'],
['eat','ate','eaten','comer'],
['fall','fell','fallen','caer'],
['feed','fed','fed','alimentar'],
['feel','felt','felt','sentir'],
['fight','fought','fought','luchar'],
['find','found','found','encontrar'],
['fly','flew','flown','volar'],
['forget','forgot','forgotten','olvidar'],
['forgive','forgave','forgiven','perdonar'],
['freeze','froze','frozen','congelar'],
['get','got','got / gotten','obtener / conseguir'],
['give','gave','given','dar'],
['go','went','gone','ir'],
['grow','grew','grown','crecer'],
['hang','hung','hung','colgar'],
['have','had','had','tener / haber'],
['hear','heard','heard','oír'],
['hide','hid','hidden','esconder'],
['hit','hit','hit','golpear'],
['hold','held','held','sostener'],
['hurt','hurt','hurt','lastimar / doler'],
['keep','kept','kept','mantener / guardar'],
['know','knew','known','saber / conocer'],
['lay','laid','laid','colocar / poner'],
['lead','led','led','guiar / liderar'],
['learn','learnt / learned','learnt / learned','aprender'],
['leave','left','left','salir / dejar'],
['lend','lent','lent','prestar'],
['let','let','let','permitir'],
['lie','lay','lain','estar acostado'],
['lose','lost','lost','perder'],
['make','made','made','hacer / fabricar'],
['mean','meant','meant','significar'],
['meet','met','met','conocer / reunirse'],
['pay','paid','paid','pagar'],
['put','put','put','poner'],
['read','read','read','leer'],
['ride','rode','ridden','montar / viajar en'],
['ring','rang','rung','sonar / llamar'],
['rise','rose','risen','elevarse / levantarse'],
['run','ran','run','correr'],
['say','said','said','decir'],
['see','saw','seen','ver'],
['sell','sold','sold','vender'],
['send','sent','sent','enviar'],
['set','set','set','colocar / fijar'],
['shake','shook','shaken','sacudir'],
['shine','shone / shined','shone / shined','brillar'],
['shoot','shot','shot','disparar'],
['show','showed','shown / showed','mostrar'],
['shut','shut','shut','cerrar'],
['sing','sang','sung','cantar'],
['sink','sank','sunk','hundirse'],
['sit','sat','sat','sentarse'],
['sleep','slept','slept','dormir'],
['speak','spoke','spoken','hablar'],
['spend','spent','spent','gastar / pasar tiempo'],
['stand','stood','stood','estar de pie'],
['steal','stole','stolen','robar'],
['swim','swam','swum','nadar'],
['take','took','taken','tomar / llevar'],
['teach','taught','taught','enseñar'],
['tear','tore','torn','rasgar'],
['tell','told','told','decir / contar'],
['think','thought','thought','pensar'],
['throw','threw','thrown','lanzar'],
['understand','understood','understood','entender'],
['wake','woke','woken','despertarse'],
['wear','wore','worn','llevar puesto'],
['win','won','won','ganar'],
['write','wrote','written','escribir']
].map(([base,past,participle,spanish], id) => ({
    id,base,past,participle,spanish
}));
